version: '3.8'
services:
  iso-simulator:
    build: .
    container_name: iso_simulator_stack
    ports:
      - "5173:5173"
      - "8583:8583"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: always
