# render.yaml
services:
  - type: web
    name: bin-check-api
    env: docker
    plan: free
    region: ohio # Change as needed
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
    ports:
      - port: 3002
        protocol: TCP
